### ISSUE TITLE
Thema ohne Text

### ISSUE THREAD

**Issue by feevonderspree** [MemoWikis/webapp#166]
Einige Seiten haben keinen Text (Inhalt) und sollten auch keinen bekommen. Die Themenliste könnte so deutlich weiter oben starten und der Nutzer kommt nicht in die Verlegenheit pseudo-relevanten Text auf einer Seite zu schreiben, die eigentlich nur eine Liste ist.
Für diese Seiten soll am Thema "Keine Texteingabe" konfiguriert werden

- Die Funktion wird per Toggle im Dreipunkt-Menü aktiviert.
- Wenn es Text auf der Seite gibt, kann die Funktion nicht angewendet werden.
- Ein Tooltip ergänzt die Funktion: "Deaktiviere die Texteingabe für eine reine Navigationsseite ohne Textinhalt."

![grafik](https://user-images.githubusercontent.com/96989427/147936735-7636b621-e884-4d8c-b0d4-bb03c6ae6183.png)

**Figma:**https://www.figma.com/file/fD6PIAMN305W6NuxP5ldNi/01-worksheet?node-id=1529%3A17271

acceptance criteria:
- on title change: green bar should still be available, and no autosave

**Comment by feevonderspree** [comment]
@RobertMischke: Wie soll sich die Funktion auf Seiten verhalten, auf denen Bereits Text existiert? Mögliches Verhalten wäre: 
1. Der Text wird lediglich ausgeblendet, bleibt aber gespeichert und kann wieder eingeblendet werden. 
2. Der Text wird ausgeblendet und gelöscht. Hier wäre ein Modal mit Hinweis auf die Löschung und zur Bestätigung sinnvoll.

**Comment by RobertMischke** [comment]
Wenn es Text auf der Seite gibt, soll die Funktion nicht angewendet werden können. 
Das Label "Text" könnte zu wenig klar sein. 
Ich denke, es wäre gut, die Tooltips gleich mitzuplanen.
