### ISSUE TITLE
TypeScript compiler Geschwindigkeit erhöhen

### ISSUE THREAD

**Issue by SchwabJustin** [MemoWikis/webapp#180]
Der TypeScript compiler ist langsam und soll beschleunigt werden. 

**mögliche Lösung**
Die Menge der Dateien die der Compiler verarbeitet reduzieren. In der tsconfig.json includes/excludes entsprechend anpassen. 

Ist-Stand:
```
"include": [
    "**/*"
  ],
  "exclude": [
    "node_modules",
    "**/*.min.js",
    "**/*.min.js.map"
```

**Comment by RobertMischke** [comment]
Obsolete after migration to vue.js
