### ISSUE TITLE
Thema kann nicht gespeichert werden

### ISSUE THREAD

**Issue by feevonderspree** [MemoWikis/webapp#232]
Das Thema [Erste-Schritte-mit-memucho](https://memucho.de/Erste-Schritte-mit-memucho/9109) kann nicht gespeichert werden, wenn weitere Bilder eingefügt werden. eine Speicherung ist nur bei Textänderungen möglich.

**Comment by tj-mai** [comment]
![image](https://user-images.githubusercontent.com/41473684/151353698-6024ab61-f8bd-458c-9580-fd3e2953cab8.png)

**Comment by tj-mai** [comment]
stage error: 413
max speichergroesse ca. 1.3MB

live:
max speichergroesse ca. 1.9MB

**Comment by Daniel-Majunke** [comment]
works fine
