### ISSUE TITLE
Thema lässt sich nicht unterordnen wenn es durch privates Thema schon untergeordnet ist

### ISSUE THREAD

**Issue by SchwabJustin** [MemoWikis/webapp#234]
Wenn ich ein öffentliches Thema in einem privaten Thema untergeordnet habe, das private Thema dann einem öffentlichen Thema unterordnen möchte und diesem öffentlichen Thema dann das andere öffentliche Thema unterordnen will, bekomme ich die Fehlermeldung, dass es schon untergeordnet ist.

Darstellung: 
(Legende: [p] = privat, => = untergeordnet)
A => B[p] => C

Wenn ich jetzt A => C machen möchte tritt der Fehler auf.

![image](https://user-images.githubusercontent.com/41286356/151362388-039728ee-0bef-499f-9f9b-6c6d2dd14e42.png)

Hängt mit Ticket #221 zusammen.

**Comment by Daniel-Majunke** [comment]
works fine
