### ISSUE TITLE
Thema verschieben

### ISSUE THREAD

**Issue by RobertMischke** [MemoWikis/webapp#249]
Es soll möglich sein, ein Thema zu einem anderen Thema zu verschieben. 

### Schritte: 
**1. Dreipunkt-Menü der Themenkarte in der Unterthemenliste**
- neuer Eintrag "Thema verschieben" 
- auch bei segmentierten Themen!
- bei Klick erscheint ein Dialog, mit Suchbox 
[Figma](https://www.figma.com/file/fD6PIAMN305W6NuxP5ldNi/%23issues-%5Bworksheet%5D?node-id=1877%3A27201)

**2. Thema verschieben-Dialog, mit Suchbox** 
- Hier kann man das Thema suchen, zu dem verschoben werden soll. 
- Usability + Design analog zu "Bestehendes Thema verknüpfen"
- Verschiebt man das Thema, wird die aktuelle Verknüpfung entfernt. 
- Confirmation-Dialog mit Link zum "Zielthema"
[Figma](https://www.figma.com/file/fD6PIAMN305W6NuxP5ldNi/%23issues-%5Bworksheet%5D?node-id=1878%3A27243)

**3. Eintrag in der Bearbeitungshistorie soll erstellt werden**
- neue Kategorie "Verschoben"
- Eintrag im bisherigen Überthema: **Verknüpfung entfernt** _"verschobenes Thema" ist nicht mehr untergeordnet_
- Eintrag im verschobenen Thema: **Verschoben** _Von "bisheriges Thema" nach "Zielthema"_
- Eintrag im Zielthema: **Verknüpfung hinzugefügt** "verschobenes Thema" ist untergeordnet
[Figma](https://www.figma.com/file/fD6PIAMN305W6NuxP5ldNi/%23issues-%5Bworksheet%5D?node-id=1884%3A27214)

**4. Oberthema verknüpfen hinzufügen**
- neuer Eintrag "Oberthema verknüpfen"
- bei Klick erscheint ein Dialog, mit Suchbox
[Figma](https://www.figma.com/file/dfUuh7WP1Fl27uZioZ4SyZ/%F0%9F%8E%A8-Design-System-%E2%80%93-UI-Kit?node-id=710%3A751)

**5. Oberthema verknüpfen-Dialog, mit Suchbox** 
- Hier kann man das Thema suchen, welches verknüpft werden soll. 
- Usability + Design analog zu "Bestehendes Thema verknüpfen"
- Confirmation-Dialog mit Link zum "Zielthema"
analog zu: [Figma](https://www.figma.com/file/fD6PIAMN305W6NuxP5ldNi/%23issues-%5Bworksheet%5D?node-id=1878%3A27243)

**Comment by juletof** [comment]
Laut Juns Test auf Live wird die Relation zum alten Parent nicht entfernt.
