### ISSUE TITLE
Wenn der Themenname zu lang ist wird er nicht in die nächste Zeile umgebrochen

### ISSUE THREAD

**Issue by SchwabJustin** [MemoWikis/webapp#267]
![image](https://user-images.githubusercontent.com/41286356/153777804-a8c52e80-6a0c-49a6-910f-3fa35a86d416.png)

**Comment by Daniel-Majunke** [comment]
If the topic name could talk, it would say: "I am a question name."

**Comment by Daniel-Majunke** [comment]
works fine
