### ISSUE TITLE
Anzahl der Fragen im Fragetab werden nicht aktualisiert wenn ein Thema verknüpft wird

### ISSUE THREAD

**Issue by feevonderspree** [MemoWikis/webapp#275]
Verknüpfe ich in der Themenliste ein Thema, wird die Anzahl der Fragen im Frage-Tab nicht angepasst. 

![Bildschirmfoto 2022-02-16 um 13 13 03](https://user-images.githubusercontent.com/96989427/154263207-de7e059a-cb52-4e73-957c-00fd78821eb2.png)
![Bildschirmfoto 2022-02-16 um 13 13 35](https://user-images.githubusercontent.com/96989427/154263214-7b743a44-4092-4e36-9a1b-4358e96993ea.png)

**Auch nicht, wenn ich in das Frage-Tab wechsle. Im Header der Frageliste wird die Fragemenge korrekt angezeigt.** 

![Bildschirmfoto 2022-02-16 um 13 14 05](https://user-images.githubusercontent.com/96989427/154263239-91ab9f27-fbd6-4496-bf94-bfbc73e7b803.png)
![Bildschirmfoto 2022-02-16 um 13 14 30](https://user-images.githubusercontent.com/96989427/154263242-9a0c4967-b758-40d6-b659-ff265e88e4db.png)

**Beim Erstellen neuer Fragen wird das Tab ebenfalls nicht aktualisiert.**

![Bildschirmfoto 2022-02-16 um 13 30 04](https://user-images.githubusercontent.com/96989427/154265049-2ba80bed-9be6-47b9-83d3-4b0a869f563d.png)

**Comment by Daniel-Majunke** [comment]
works fine

**Comment by Daniel-Majunke** [comment]
![Image](https://github.com/MemoWikis/webapp/assets/29574334/dd08470c-bdfb-4d8f-9973-1e4d75d78c2c)
