### ISSUE TITLE
Fragen die im "Erweierte Optionen-Modal" erstellt werden sind nicht automatisch im Wunschwissen

### ISSUE THREAD

**Issue by feevonderspree** [MemoWikis/webapp#276]
Fragen, die über die "Erweierten Optionen" im Modal erstellt werden sind nicht automatisch im Wunschwissen enthalten. 

Erstellte Fragen sollen per default im Wunschwissen des Erstellers sein. 
Im Modal Soll das Wunschwissen per default aktiv sein. 

![Bildschirmfoto 2022-02-16 um 13 32 59](https://user-images.githubusercontent.com/96989427/154265990-6824d690-4ae8-4926-bfb0-1c96c7842ab6.png)
![Bildschirmfoto 2022-02-16 um 13 37 12](https://user-images.githubusercontent.com/96989427/154266054-d1ccb77f-27b6-41bb-83d3-1c60bbf92608.png)

**Comment by Daniel-Majunke** [comment]
works fine
