### ISSUE TITLE
Bibliotheken / Fonts nicht mehr über CDN

### ISSUE THREAD

**Issue by RobertMischke** [MemoWikis/webapp#284]
Aus rechtlichen Gründen sollen Bibliotheken / Fonts nicht mehr über CDN eingebunden werden. 

1: Was binden wir per CDN ein? 
2: Über memucho.de ausliefern, nicht mehr über CDN.

Aus Performance-Sicht sollte uns das nicht groß negativ beeinflussen, da aktuelle Browser kein Choss-Domain-Caching mehr erlauben.

**Comment by Daniel-Majunke** [comment]
no cdns since nuxt
