### ISSUE TITLE
Landing-Page: Info-Banner und crumb trail

### ISSUE THREAD

**Issue by RobertMischke** [MemoWikis/webapp#298]
1: Auf der Landing-Page sollen die gleichen Banner erscheinen wie auf den Themen-Seiten
2: Es soll ein crumb-trail angzeigt werden 

![image](https://user-images.githubusercontent.com/156185/157201655-df5238f1-6fc0-4c03-9746-b61bef34b5c1.png)

**Comment by schmaiki** [comment]
**Ich bin gerade beim Model:**

https://github.com/memucho/webapp/blob/Info-Banner/src/TrueOrFalse.Frontend.Web/Views/Questions/Answer/AnswerQuestionModel.cs#L241-L254

Url: http://localhost:61213/Fragen/Wer-war-Fussballweltmeister/128/1

_**Debuggerausgabe:**_

QuestionHasParentCategories = question.Categories.Any(); 

```
QuestionHasParentCategories = true, question = Id =128
```

PrimaryCategory = GetPrimaryCategory.GetForQuestion(question);
```
PrimaryCategory = Id=29 Name="Microsoft", question = Id = 128
```

AnalyticsFooterModel = new AnalyticsFooterModel(PrimaryCategory, true);
```
AnalyticsFooterModel = null, 
PrimaryCategory = Id=29 Name="Microsoft"
```


**Was ausgegeben wird:**

Nach dem laden der Frage, erscheint folgendes:
<img width="581" alt="image" src="https://user-images.githubusercontent.com/73941088/174579400-14c9e0ae-9788-45a8-941d-33a0b987f2e1.png">


**Was ich erwarte als Ausgabe:

Eigentlich müsste eine Frage zur Fußballweltmeister dargestellt werden.

**Datenbankeintrag zur Frage : Weltmeister
```
Solution:
{"Rows":{"2002":"Brasilien","2006":"Italien","2010":"Spanien"}}
```

**Frage:**
Wieso gibt er eine andere Frage aus?

**Comment by juletof** [comment]
Beim Crumbtrail steht oben "Fehler"
