### ISSUE TITLE
Profilbilder werden in firefox nicht korrekt angezeigt

### ISSUE THREAD

**Issue by feevonderspree** [MemoWikis/webapp#340]
Mir werden das Profilbild von Daniel und weiteren Nutzern in firefox nicht angezeigt. In Chrome und Safari ist die Ansicht korrekt. 
Das geschieht unabhängig davon, ob ich angemeldet bin oder nicht. 
Einige weitere User bei denen das auftritt, habe ich unten in eine Liste kopiert. 
geteste Firefox Version: 97.0.2 + 98.0.2

Userliste: 
- https://memucho.de/Nutzer/Michi-The-Bear-Hangl/1475
- https://memucho.de/Nutzer/Suela-Jace/1402
- https://memucho.de/Nutzer/Elisabeth-Dinh/1399
- https://memucho.de/Nutzer/Aida-ZenAida-Bajraktarevic/315
- https://memucho.de/Nutzer/Thorsten-Belzer/666
- https://memucho.de/Nutzer/Mariusz-Zawilski/2216
und weitere

![Bildschirmfoto 2022-04-01 um 10 14 33](https://user-images.githubusercontent.com/96989427/161225252-60d89f45-47fc-4666-ba6d-c9b7890c499c.png)

![Bildschirmfoto 2022-04-01 um 10 14 46](https://user-images.githubusercontent.com/96989427/161224128-7331a6bb-cad4-4b02-82d7-486d4c7f6f4f.png)

![Bildschirmfoto 2022-04-01 um 10 13 04](https://user-images.githubusercontent.com/96989427/161223353-490f8104-2071-4c8a-88e1-8e9e21a753af.png)

**Comment by tj-mai** [comment]
problem can't be reproduced anymore after nuxt migration
