### ISSUE TITLE
Themenliste: In der mobilen Ansicht soll das Dreipunkt-Menü direkt gezeigt werden. 

### ISSUE THREAD

**Issue by feevonderspree** [MemoWikis/webapp#341]
In der mobilen Ansicht der Themenliste sollte das Dreipunktmenü sofort angezeigt werden, also nicht erst beim Hovern, bzw. Click. 

- bitte für die einfache und für die segmentierte Ansicht
- einfaches graues Icon ohne Hover Effekt nutzen

![grafik](https://user-images.githubusercontent.com/96989427/161227075-3b2fa730-a09c-44f9-93ab-d7cc3f12d2b7.png)
![grafik](https://user-images.githubusercontent.com/96989427/161227108-da6a9361-4741-4102-b313-8d86ac7c27a3.png)

**Comment by Daniel-Majunke** [comment]
works
