### ISSUE TITLE
Fehlerhafte Darstellung des Verknüpfen-Dialogs

### ISSUE THREAD

**Issue by feevonderspree** [MemoWikis/webapp#408]
Bei allen heute neu zu meinem Wiki hinzugefügten Themen wird aktuell der Dialog nicht korrekt / vollständig angezeigt.

Link Figma: 
erster Entwurf: https://www.figma.com/file/fD6PIAMN305W6NuxP5ldNi/%F0%9F%AA%84-%23Issues-%5Bworksheet%5D?node-id=2584%3A55630
aktuelle Überarbeitung: https://www.figma.com/file/KUHoWljwQPvNlov0mzrhO2/%23-Ideen-%5Bdrafts%5D?node-id=2526%3A36021

![grafik](https://user-images.githubusercontent.com/96989427/194904766-bbb8fc2d-9907-49bd-a472-9666565a1f1a.png)
 
![grafik](https://user-images.githubusercontent.com/96989427/194904730-6414453d-2759-4bec-bf3c-95073125c0ab.png)

**Comment by juletof** [comment]
Gibt es eine Referenz, wie es eigentlich aussehen soll?

**Comment by feevonderspree** [comment]
> @feevonderspree Gibt es eine Referenz, wie es eigentlich aussehen soll?

Das persönliche Wiki soll stets vorausgewählt sein. 
Zuletzt ausgewählte themen erscheinen nur, wenn die Aktion vorher bereits durchgeführt wurde

Ich habe den Fgma-Link im ticket oben ergänzt!

![Bildschirmfoto 2022-11-10 um 12 06 19](https://user-images.githubusercontent.com/96989427/201075356-74e54c6a-f26e-4943-a3da-032d3501d87a.png)
