### ISSUE TITLE
add persistent login for user/pw auth (normal users, NOT google/fb)

### ISSUE THREAD

**Issue by tj-mai** [MemoWikis/webapp#680]
- recommended best practice is give the user the choice, so add the checkbox back

acceptance criteria:
- checkbox for user on login
- reuse the old persistent login logic

after feedback/review implement solution

previously suggested solution:
Generate a secure key on the server.
Encrypt the user ID with the secure key.
Encrypt the expiration date with the secure key.
Write the encrypted user ID and expiration date into the cookie.
Upon login:
Decrypt both values using the key on the server.
Check the expiration date.
Retrieve the user ID.
Log in if both are valid.
Set a new cookie with an extended expiration date.

update:
- jun provides an initial request/nuxt middleware to handle the persistent login/cookies
-

**Comment by RobertMischke** [comment]
In the beginning, we will implement the most simple solution. Without stolen cookie detection and re-login for certain areas. I added an issue for future security improvements: #871

**Comment by Daniel-Majunke** [comment]
local, stage and prod test
