### ISSUE TITLE
Feed (new Tab)

### ISSUE THREAD

**Issue by Daniel-Majunke** [MemoWikis/webapp#777]
https://github.com/MemoWikis/webapp/issues/373

focus on minimal working version

- only visible to user (private changes should not be visible to other  users)
- [ ] feed replaces history

- [ ] topic text change (revertable)
- [ ] topic title change 
- [ ] topic published
- [ ] topic set to private (only for self)
- [ ] topic creation
- [ ] topic added 
- [ ] topic removed (revertable?)
- [ ] topic parent added (anonymous if parent is private)
- [ ] question comment add
- [ ] question comment resolved
- [ ] question removed
- [ ] question added (hide if question is private)
- [ ] question published
- [ ] question set to private (only for self)
- [ ] question text change
- [ ] question related topic add (anonymous if topic is private)
- [ ] question related topic remove

**Comment by tj-mai** [comment]
duplicate to #1096
