### ISSUE TITLE
fix:  "CategoryRelations - Sort: Broken Link Start - TopicId:.., RelationId:..."

### ISSUE THREAD

**Issue by Daniel-Majunke** [MemoWikis/webapp#892]
On startup we see broken link errors. 

Investigate, and fix if really obvious. Otherwise discuss.

**Comment by Daniel-Majunke** [comment]
- don't spend too much time on it
- fix broken links manually

**Comment by tj-mai** [comment]
fixed:
- 2298
- 332
- 9167
