### ISSUE TITLE
iOS 16 / 15: memucho icon is stretched

### ISSUE THREAD

**Issue by RobertMischke** [MemoWikis/webapp#900]
iPhone 14 / iOS v16.4
![Image](https://github.com/MemoWikis/webapp/assets/156185/f90265f2-ed2a-438f-9444-aa9450a73ed4)

iPhone 15 /iOS v17.3
![Image](https://github.com/MemoWikis/webapp/assets/156185/1c9488c8-2073-4bd7-9e43-e0d2b6408395)

iPhone 13 /iOS v15.x

and probably others

**Comment by Daniel-Majunke** [comment]
releated #954

**Comment by tj-mai** [comment]
not fixed
